# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c
sudo: required
dist: bionic

matrix:
  include:
    - name: "Linux tests"
      os: linux
      dist: bionic
      sudo: required

    - name: "macOS tests"
      os: osx

    - name: "Linux tests conditional Suggests"
      os: linux
      dist: bionic
      sudo: required
      env: _R_CHECK_DEPENDS_ONLY_="true"

env:
  global:
    - USE_BSPM="true"
      
before_install:
  - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_all

script:
  - ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

